// Code generated by MockGen. DO NOT EDIT.
// Source: create_book.go
//
// Generated by this command:
//
//	mockgen -source=create_book.go -destination=mocks/create_book.go
//

// Package mock_handlers is a generated GoMock package.
package mock_handlers

import (
	domain "book-api/internal/domain"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCreateBookService is a mock of CreateBookService interface.
type MockCreateBookService struct {
	ctrl     *gomock.Controller
	recorder *MockCreateBookServiceMockRecorder
}

// MockCreateBookServiceMockRecorder is the mock recorder for MockCreateBookService.
type MockCreateBookServiceMockRecorder struct {
	mock *MockCreateBookService
}

// NewMockCreateBookService creates a new mock instance.
func NewMockCreateBookService(ctrl *gomock.Controller) *MockCreateBookService {
	mock := &MockCreateBookService{ctrl: ctrl}
	mock.recorder = &MockCreateBookServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCreateBookService) EXPECT() *MockCreateBookServiceMockRecorder {
	return m.recorder
}

// CreateBook mocks base method.
func (m *MockCreateBookService) CreateBook(ctx context.Context, req domain.BookEntity) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBook", ctx, req)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBook indicates an expected call of CreateBook.
func (mr *MockCreateBookServiceMockRecorder) CreateBook(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBook", reflect.TypeOf((*MockCreateBookService)(nil).CreateBook), ctx, req)
}
