// Code generated by MockGen. DO NOT EDIT.
// Source: delete_book.go
//
// Generated by this command:
//
//	mockgen -source=delete_book.go -destination=mocks/delete_book.go
//

// Package mock_handlers is a generated GoMock package.
package mock_handlers

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDeleteBookService is a mock of DeleteBookService interface.
type MockDeleteBookService struct {
	ctrl     *gomock.Controller
	recorder *MockDeleteBookServiceMockRecorder
}

// MockDeleteBookServiceMockRecorder is the mock recorder for MockDeleteBookService.
type MockDeleteBookServiceMockRecorder struct {
	mock *MockDeleteBookService
}

// NewMockDeleteBookService creates a new mock instance.
func NewMockDeleteBookService(ctrl *gomock.Controller) *MockDeleteBookService {
	mock := &MockDeleteBookService{ctrl: ctrl}
	mock.recorder = &MockDeleteBookServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeleteBookService) EXPECT() *MockDeleteBookServiceMockRecorder {
	return m.recorder
}

// DeleteBook mocks base method.
func (m *MockDeleteBookService) DeleteBook(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBook", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBook indicates an expected call of DeleteBook.
func (mr *MockDeleteBookServiceMockRecorder) DeleteBook(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBook", reflect.TypeOf((*MockDeleteBookService)(nil).DeleteBook), ctx, id)
}
