// Code generated by MockGen. DO NOT EDIT.
// Source: get_all_book.go
//
// Generated by this command:
//
//	mockgen -source=get_all_book.go -destination=mocks/get_all_book.go
//

// Package mock_handlers is a generated GoMock package.
package mock_handlers

import (
	domain "book-api/internal/domain"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockGetAllBookService is a mock of GetAllBookService interface.
type MockGetAllBookService struct {
	ctrl     *gomock.Controller
	recorder *MockGetAllBookServiceMockRecorder
}

// MockGetAllBookServiceMockRecorder is the mock recorder for MockGetAllBookService.
type MockGetAllBookServiceMockRecorder struct {
	mock *MockGetAllBookService
}

// NewMockGetAllBookService creates a new mock instance.
func NewMockGetAllBookService(ctrl *gomock.Controller) *MockGetAllBookService {
	mock := &MockGetAllBookService{ctrl: ctrl}
	mock.recorder = &MockGetAllBookServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetAllBookService) EXPECT() *MockGetAllBookServiceMockRecorder {
	return m.recorder
}

// GetBooks mocks base method.
func (m *MockGetAllBookService) GetBooks(ctx context.Context) ([]domain.BookEntity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBooks", ctx)
	ret0, _ := ret[0].([]domain.BookEntity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBooks indicates an expected call of GetBooks.
func (mr *MockGetAllBookServiceMockRecorder) GetBooks(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBooks", reflect.TypeOf((*MockGetAllBookService)(nil).GetBooks), ctx)
}
