// Code generated by MockGen. DO NOT EDIT.
// Source: get_book_by_ids.go
//
// Generated by this command:
//
//	mockgen -source=get_book_by_ids.go -destination=mocks/get_book_by_ids.go
//

// Package mock_handlers is a generated GoMock package.
package mock_handlers

import (
	domain "book-api/internal/domain"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockGetBookByIdsService is a mock of GetBookByIdsService interface.
type MockGetBookByIdsService struct {
	ctrl     *gomock.Controller
	recorder *MockGetBookByIdsServiceMockRecorder
}

// MockGetBookByIdsServiceMockRecorder is the mock recorder for MockGetBookByIdsService.
type MockGetBookByIdsServiceMockRecorder struct {
	mock *MockGetBookByIdsService
}

// NewMockGetBookByIdsService creates a new mock instance.
func NewMockGetBookByIdsService(ctrl *gomock.Controller) *MockGetBookByIdsService {
	mock := &MockGetBookByIdsService{ctrl: ctrl}
	mock.recorder = &MockGetBookByIdsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetBookByIdsService) EXPECT() *MockGetBookByIdsServiceMockRecorder {
	return m.recorder
}

// GetBookByIds mocks base method.
func (m *MockGetBookByIdsService) GetBookByIds(ctx context.Context, ids []int) ([]domain.BookEntity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBookByIds", ctx, ids)
	ret0, _ := ret[0].([]domain.BookEntity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBookByIds indicates an expected call of GetBookByIds.
func (mr *MockGetBookByIdsServiceMockRecorder) GetBookByIds(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBookByIds", reflect.TypeOf((*MockGetBookByIdsService)(nil).GetBookByIds), ctx, ids)
}
