// Code generated by MockGen. DO NOT EDIT.
// Source: update_book.go
//
// Generated by this command:
//
//	mockgen -source=update_book.go -destination=mocks/update_book.go
//

// Package mock_handlers is a generated GoMock package.
package mock_handlers

import (
	domain "book-api/internal/domain"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockUpdateBookService is a mock of UpdateBookService interface.
type MockUpdateBookService struct {
	ctrl     *gomock.Controller
	recorder *MockUpdateBookServiceMockRecorder
}

// MockUpdateBookServiceMockRecorder is the mock recorder for MockUpdateBookService.
type MockUpdateBookServiceMockRecorder struct {
	mock *MockUpdateBookService
}

// NewMockUpdateBookService creates a new mock instance.
func NewMockUpdateBookService(ctrl *gomock.Controller) *MockUpdateBookService {
	mock := &MockUpdateBookService{ctrl: ctrl}
	mock.recorder = &MockUpdateBookServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUpdateBookService) EXPECT() *MockUpdateBookServiceMockRecorder {
	return m.recorder
}

// UpdateBook mocks base method.
func (m *MockUpdateBookService) UpdateBook(ctx context.Context, req domain.BookEntity) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBook", ctx, req)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateBook indicates an expected call of UpdateBook.
func (mr *MockUpdateBookServiceMockRecorder) UpdateBook(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBook", reflect.TypeOf((*MockUpdateBookService)(nil).UpdateBook), ctx, req)
}
