version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - inner_host 
      
  book-api:
    image: book-api:latest
    env_file:
      - .env
    volumes:
      - ./config/config.yaml:/app/config.yaml
    ports:
      - 4000:4000
    command: ["/bin/sh", "-c", "ls -l /app && cat /app/config.yaml && /app/book-api -config /config.yaml"]
    networks:
      - inner_host
    depends_on:
      - db

  migrator:
    image: migrate/migrate
    networks:
      - inner_host
    volumes:
      - ./migrations:/migrations
    env_file:
      - .env
    command: ["-path", "/migrations", "-database", "postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=disable ${MIGRATION_COMMAND} ${MIGRATION_VERSION}"]
    links:
      - db

networks:
  inner_host:
    driver: "bridge"
