version: '3.8'

services:
  db:
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234qwerty
    image: postgres:latest
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    ports:
      - 5436:5432
    networks:
      - inner_host
  book-api:
    build: ./
    command: ./book-api
    env_file:
      - ./configs/config.env
    ports:
      - 4000:4000
    networks:
      - inner_host
    depends_on:
      - db
networks:
  inner_host:
    driver: "bridge"