version: '3.8'

services:
  db:
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234qwerty
    image: postgres:latest
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    ports:
      - 5436:5432
    networks:
      - inner_host
  book-api:
    build: ./
    command: >
      sh -c "migrate -path ./schema -database 'postgres://postgres:1234qwerty@db:5432/postgres?sslmode=disable' up &&
             ./book-api"
    ports:
      - 4000:4000
    environment:
      - SERVER_PORT=4000
      - DB_HOST=db
    networks:
      - inner_host
    depends_on:
      - db
networks:
  inner_host:
    driver: "bridge"