// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go
//
// Generated by this command:
//
//	mockgen -source=repository.go -destination=./mocks/repository.go
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	domain "book-api/internal/domain"
	transaction "book-api/internal/transaction"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockBookRepository is a mock of BookRepository interface.
type MockBookRepository struct {
	ctrl     *gomock.Controller
	recorder *MockBookRepositoryMockRecorder
}

// MockBookRepositoryMockRecorder is the mock recorder for MockBookRepository.
type MockBookRepositoryMockRecorder struct {
	mock *MockBookRepository
}

// NewMockBookRepository creates a new mock instance.
func NewMockBookRepository(ctrl *gomock.Controller) *MockBookRepository {
	mock := &MockBookRepository{ctrl: ctrl}
	mock.recorder = &MockBookRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBookRepository) EXPECT() *MockBookRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockBookRepository) Create(ctx context.Context, tx transaction.Transaction, book *domain.BookEntity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, tx, book)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockBookRepositoryMockRecorder) Create(ctx, tx, book any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockBookRepository)(nil).Create), ctx, tx, book)
}

// Delete mocks base method.
func (m *MockBookRepository) Delete(ctx context.Context, tx transaction.Transaction, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, tx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockBookRepositoryMockRecorder) Delete(ctx, tx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockBookRepository)(nil).Delete), ctx, tx, id)
}

// GetAll mocks base method.
func (m *MockBookRepository) GetAll(ctx context.Context) ([]domain.BookEntity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx)
	ret0, _ := ret[0].([]domain.BookEntity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockBookRepositoryMockRecorder) GetAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockBookRepository)(nil).GetAll), ctx)
}

// GetByIds mocks base method.
func (m *MockBookRepository) GetByIds(ctx context.Context, ids []int) ([]domain.BookEntity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIds", ctx, ids)
	ret0, _ := ret[0].([]domain.BookEntity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIds indicates an expected call of GetByIds.
func (mr *MockBookRepositoryMockRecorder) GetByIds(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIds", reflect.TypeOf((*MockBookRepository)(nil).GetByIds), ctx, ids)
}

// Update mocks base method.
func (m *MockBookRepository) Update(ctx context.Context, tx transaction.Transaction, book *domain.BookEntity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, tx, book)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockBookRepositoryMockRecorder) Update(ctx, tx, book any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockBookRepository)(nil).Update), ctx, tx, book)
}

// MockAuthorRepository is a mock of AuthorRepository interface.
type MockAuthorRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAuthorRepositoryMockRecorder
}

// MockAuthorRepositoryMockRecorder is the mock recorder for MockAuthorRepository.
type MockAuthorRepositoryMockRecorder struct {
	mock *MockAuthorRepository
}

// NewMockAuthorRepository creates a new mock instance.
func NewMockAuthorRepository(ctrl *gomock.Controller) *MockAuthorRepository {
	mock := &MockAuthorRepository{ctrl: ctrl}
	mock.recorder = &MockAuthorRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthorRepository) EXPECT() *MockAuthorRepositoryMockRecorder {
	return m.recorder
}

// CreateOrUpdate mocks base method.
func (m *MockAuthorRepository) CreateOrUpdate(ctx context.Context, tx transaction.Transaction, author *domain.BookAuthor) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrUpdate", ctx, tx, author)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateOrUpdate indicates an expected call of CreateOrUpdate.
func (mr *MockAuthorRepositoryMockRecorder) CreateOrUpdate(ctx, tx, author any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrUpdate", reflect.TypeOf((*MockAuthorRepository)(nil).CreateOrUpdate), ctx, tx, author)
}

// GetByName mocks base method.
func (m *MockAuthorRepository) GetByName(ctx context.Context, name string) (*domain.BookAuthor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByName", ctx, name)
	ret0, _ := ret[0].(*domain.BookAuthor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByName indicates an expected call of GetByName.
func (mr *MockAuthorRepositoryMockRecorder) GetByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByName", reflect.TypeOf((*MockAuthorRepository)(nil).GetByName), ctx, name)
}

// MockGenreRepository is a mock of GenreRepository interface.
type MockGenreRepository struct {
	ctrl     *gomock.Controller
	recorder *MockGenreRepositoryMockRecorder
}

// MockGenreRepositoryMockRecorder is the mock recorder for MockGenreRepository.
type MockGenreRepositoryMockRecorder struct {
	mock *MockGenreRepository
}

// NewMockGenreRepository creates a new mock instance.
func NewMockGenreRepository(ctrl *gomock.Controller) *MockGenreRepository {
	mock := &MockGenreRepository{ctrl: ctrl}
	mock.recorder = &MockGenreRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGenreRepository) EXPECT() *MockGenreRepositoryMockRecorder {
	return m.recorder
}

// DeleteBookGenre mocks base method.
func (m *MockGenreRepository) DeleteBookGenre(ctx context.Context, tx transaction.Transaction, bookId int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBookGenre", ctx, tx, bookId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBookGenre indicates an expected call of DeleteBookGenre.
func (mr *MockGenreRepositoryMockRecorder) DeleteBookGenre(ctx, tx, bookId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBookGenre", reflect.TypeOf((*MockGenreRepository)(nil).DeleteBookGenre), ctx, tx, bookId)
}

// GetByBookId mocks base method.
func (m *MockGenreRepository) GetByBookId(ctx context.Context, bookId int) ([]domain.BookGenre, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByBookId", ctx, bookId)
	ret0, _ := ret[0].([]domain.BookGenre)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByBookId indicates an expected call of GetByBookId.
func (mr *MockGenreRepositoryMockRecorder) GetByBookId(ctx, bookId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByBookId", reflect.TypeOf((*MockGenreRepository)(nil).GetByBookId), ctx, bookId)
}

// UpsertGenreToBook mocks base method.
func (m *MockGenreRepository) UpsertGenreToBook(ctx context.Context, tx transaction.Transaction, bookId, genreId int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertGenreToBook", ctx, tx, bookId, genreId)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertGenreToBook indicates an expected call of UpsertGenreToBook.
func (mr *MockGenreRepositoryMockRecorder) UpsertGenreToBook(ctx, tx, bookId, genreId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertGenreToBook", reflect.TypeOf((*MockGenreRepository)(nil).UpsertGenreToBook), ctx, tx, bookId, genreId)
}
