# Server configurations
server: 
  port: 4000
  host: 127.0.0.1
# Database configurations
db: 
  host: '127.0.0.1'
  port: 5432
  user: 'postgres'
  password: '1234qwerty'
  dbname: 'postgres'
  ssl: 'disable '