definitions:
  dto.BookResponse:
    properties:
      author_name:
        type: string
      cover:
        items:
          type: integer
        type: array
      description:
        type: string
      genres:
        items:
          type: string
        type: array
      id:
        type: integer
      name:
        type: string
      page_count:
        type: integer
      rate:
        type: integer
    type: object
  dto.CreateBookRequest:
    properties:
      author_name:
        type: string
      cover:
        items:
          type: integer
        type: array
      description:
        type: string
      genres:
        items:
          type: integer
        type: array
      name:
        type: string
      page_count:
        minimum: 1
        type: integer
      rate:
        maximum: 10
        minimum: 0
        type: number
    required:
    - author_name
    - cover
    - description
    - genres
    - name
    - page_count
    type: object
  dto.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  dto.SimpleResponse:
    properties:
      id:
        type: integer
    type: object
  dto.UpdateBookRequest:
    properties:
      author_name:
        type: string
      cover:
        items:
          type: integer
        type: array
      description:
        type: string
      genres:
        items:
          type: integer
        type: array
      name:
        type: string
      page_count:
        minimum: 1
        type: integer
      rate:
        maximum: 10
        minimum: 0
        type: number
    required:
    - author_name
    - cover
    - description
    - genres
    - name
    - page_count
    type: object
host: localhost:4000
info:
  contact: {}
  description: This is a sample server.
  title: Book API
  version: "1.0"
paths:
  /books:
    delete:
      consumes:
      - application/json
      description: Delete a book entry from the system using the book's ID
      parameters:
      - description: Book ID
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: 'Bad Request: Invalid parameter or deletion issue'
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Delete a book by ID
      tags:
      - Books
    get:
      consumes:
      - application/json
      description: Retrieve a list of books by providing their IDs as a comma-separated
        query parameter.
      parameters:
      - description: Comma-separated list of book IDs
        in: query
        name: ids
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: List of books
          schema:
            items:
              $ref: '#/definitions/dto.BookResponse'
            type: array
        "400":
          description: Error retrieving books
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Retrieve books by their IDs
      tags:
      - Books
    post:
      consumes:
      - application/json
      description: Create a new book entry in the system
      parameters:
      - description: Create Book Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.CreateBookRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Book created successfully
          schema:
            $ref: '#/definitions/dto.SimpleResponse'
        "400":
          description: Invalid data or validation failed
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Create a new book
      tags:
      - Books
    put:
      consumes:
      - application/json
      description: Update the details of an existing book in the system
      parameters:
      - description: Update Book Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.UpdateBookRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Book updated successfully
          schema:
            $ref: '#/definitions/dto.BookResponse'
        "400":
          description: Invalid data or validation failed
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Update an existing book
      tags:
      - Books
swagger: "2.0"
